#!/usr/bin/env python3
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "js" / "app.js"
T = "di" + "v"  # html element


def write_app():
    lines = []
    a = lines.append
    a("(function () {")
    a('  const NAV = [')
    a('    { id: "overview", label: "总览", icon: "◉" },')
    a('    { id: "routes", label: "路由", icon: "⇄" },')
    a('    { id: "waf", label: "WAF", icon: "⛨" },')
    a('    { id: "tls", label: "TLS", icon: "🔒" },')
    a('    { id: "config", label: "配置", icon: "⌘" },')
    a('    { id: "logs", label: "日志", icon: "≡" },')
    a("  ];")
    a("  let savedYaml = MOCK.yamlBaseline.trim();")
    a("  const $ = (sel, root = document) => root.querySelector(sel);")
    a("  const $$ = (sel, root = document) => [...root.querySelectorAll(sel)];")
    a("  function toast(msg, type) {")
    a(f'    const el = document.createElement("{T}");')
    a('    el.className = "toast " + (type || "success");')
    a("    el.textContent = msg;")
    a('    $("#toasts").appendChild(el);')
    a("    setTimeout(function () { el.remove(); }, 4000);")
    a("  }")
    a("  function hostTypeBadge(t) {")
    a('    var c = t === "regex" ? "badge-regex" : t === "wildcard" ? "badge-wildcard" : "badge-exact";')
    a('    return \'<span class="badge \' + c + \'">\' + t + "</span>";')
    a("  }")
    a("  function navigate(pageId) {")
    a('    $$(".nav button").forEach(function (b) { b.classList.toggle("active", b.dataset.page === pageId); });')
    a('    $$(".page").forEach(function (p) { p.classList.toggle("active", p.dataset.page === pageId); });')
    a("    location.hash = pageId;")
    a("  }")
    a("  function initNav() {")
    a('    var nav = $("#nav");')
    a("    NAV.forEach(function (item) {")
    a('      var btn = document.createElement("button");')
    a('      btn.type = "button";')
    a("      btn.dataset.page = item.id;")
    a('      btn.innerHTML = \'<span class="icon">\' + item.icon + "</span>" + item.label;')
    a("      btn.addEventListener(\"click\", function () { navigate(item.id); });")
    a("      nav.appendChild(btn);")
    a("    });")
    a('    var hash = (location.hash || "#overview").slice(1);')
    a("    navigate(NAV.some(function (n) { return n.id === hash; }) ? hash : \"overview\");")
    a('    window.addEventListener("hashchange", function () {')
    a('      var h = (location.hash || "#overview").slice(1);')
    a("      if (NAV.some(function (n) { return n.id === h; })) navigate(h);")
    a("    });")
    a('    $$("[data-goto]").forEach(function (el) {')
    a("      el.addEventListener(\"click\", function () { navigate(el.dataset.goto); });")
    a("    });")
    a("  }")
    a("  function card(cls, label, value, sub) {")
    a(
        f"    return '<{T} class=\"card ' + cls + '\"><{T} class=\"label\">' + label + '</{T}><{T} class=\"value\">' + value + '</{T}><{T} class=\"sub\">' + sub + '</{T}></{T}>';"
    )
    a("  }")
    a("  function renderOverview() {")
    a("    var i = MOCK.instance;")
    a('    $("#sidebar-config-path").textContent = i.configPath;')
    a("    var certWarn = MOCK.certs.filter(function (c) { return c.status !== \"ok\"; }).length;")
    a('    var wafLabel = i.wafEnabled ? (i.wafLogOnly ? "审计" : "拦截") : "关";')
    a('    $("#overview-cards").innerHTML = [')
    a('      card("ok", "状态", "运行中", "PID " + i.pid + " · " + i.uptime),')
    a('      card("", "版本", i.version, "配置 hash " + i.configHash),')
    a('      card("", "监听", String(i.listenHTTP), "HTTPS " + i.listenHTTPS),')
    a('      card("", "路由规则", String(i.rulesCount), "上次 reload " + i.lastReload),')
    a('      card(i.wafLogOnly ? "warn" : "", "WAF", wafLabel, "log_only=" + i.wafLogOnly),')
    a('      card(certWarn ? "warn" : "ok", "证书", certWarn ? certWarn + " 需关注" : "正常", "TLS 证书有效期"),')
    a("    ].join(\"\");")
    a("    var events = MOCK.wafEvents.slice(0, 4).map(function (e) {")
    a('      return "<tr><td>" + e.time + "</td><td><span class=\\"badge badge-" + e.action + "\\">" + e.action + "</span></td><td>" + e.rule + "</td><td>" + e.host + "</td><td>" + escapeHtml(e.path) + "</td></tr>";')
    a("    });")
    a('    $("#overview-events").innerHTML = "<table class=\\"data\\"><thead><tr><th>时间</th><th>动作</th><th>规则</th><th>Host</th><th>Path</th></tr></thead><tbody>" + events.join("") + "</tbody></table>";')
    a("  }")
    a("  function escapeHtml(s) {")
    a("    return String(s).replace(/&/g, \"&amp;\").replace(/</g, \"&lt;\").replace(/>/g, \"&gt;\");")
    a("  }")
    a("  function renderRoutes(filter) {")
    a('    var q = (filter || "").toLowerCase();')
    a("    var rows = MOCK.routes.filter(function (r) {")
    a("      if (!q) return true;")
    a('      return (r.host + " " + r.path + " " + r.target + " " + r.backendType).toLowerCase().indexOf(q) >= 0;')
    a("    }).map(function (r) {")
    a('      return "<tr><td><code>" + escapeHtml(r.host) + "</code></td><td>" + hostTypeBadge(r.hostType) + "</td><td>" + escapeHtml(r.path) + "</td><td>" + r.backendType + "</td><td><code>" + escapeHtml(r.target) + "</code></td></tr>";')
    a("    });")
    a('    $("#routes-table tbody").innerHTML = rows.join("") || \'<tr><td colspan="5" class="empty-hint">无匹配规则</td></tr>\';')
    a("  }")
    a("  function matchRoute(host, path) {")
    a('    host = (host || "").toLowerCase();')
    a('    path = path || "/";')
    a('    if (path.indexOf("/") !== 0) path = "/" + path;')
    a("    for (var i = 0; i < MOCK.routes.length; i++) {")
    a("      var r = MOCK.routes[i];")
    a('      if (r.hostType === "exact" && r.host.toLowerCase() !== host) continue;')
    a('      if (r.hostType === "wildcard") {')
    a('        var suffix = r.host.replace(/^\\*\\./, "");')
    a("        if (host.indexOf(suffix.toLowerCase(), host.length - suffix.length) === -1 && host !== suffix.toLowerCase()) continue;")
    a("      }")
    a('      if (r.hostType === "regex") {')
    a("        try { if (!new RegExp(r.host, \"i\").test(host)) continue; } catch (e) { continue; }")
    a("      }")
    a('      if (r.pathType === "exact" && r.path !== path) continue;')
    a('      if (r.pathType === "prefix" && r.path !== "/" && path.indexOf(r.path) !== 0) continue;')
    a("      return r;")
    a("    }")
    a("    return null;")
    a("  }")
    a("  function runMatch() {")
    a('    var host = $("#match-host").value.trim();')
    a('    var path = $("#match-path").value.trim();')
    a("    var hit = matchRoute(host, path);")
    a('    var box = $("#match-result");')
    a("    if (!hit) {")
    a('      box.className = "match-result miss";')
    a('      box.innerHTML = "<h3>未命中</h3><p>将走 fallback 或返回 404（原型模拟）。</p>";')
    a("      return;")
    a("    }")
    a('    box.className = "match-result hit";')
    a('    box.innerHTML = "<h3>命中规则 #" + hit.id + "</h3><dl><dt>Host</dt><dd>" + escapeHtml(hit.host) + " (" + hit.hostType + ")</dd><dt>Path</dt><dd>" + escapeHtml(hit.path) + "</dd><dt>Backend</dt><dd>" + hit.backendType + "</dd><dt>目标</dt><dd><code>" + escapeHtml(hit.target) + "</code></dd><dt>WAF</dt><dd>" + hit.waf + "</dd></dl>";')
    a("  }")
    a("  function renderWaf() {")
    a("    var i = MOCK.instance;")
    a('    $("#waf-cards").innerHTML = [')
    a('      card("", "状态", i.wafEnabled ? "已启用" : "关闭", "全局 waf.enabled"),')
    a('      card(i.wafLogOnly ? "warn" : "", "模式", i.wafLogOnly ? "仅审计" : "拦截", "log_only"),')
    a('      card("", "内置规则", "已加载", "builtin: true"),')
    a('    ].join("");')
    a("    renderWafTable($(\"#waf-filter\").value);")
    a("  }")
    a("  function renderWafTable(filter) {")
    a("    var rows = MOCK.wafEvents.filter(function (e) { return filter === \"all\" || e.action === filter; }).map(function (e) {")
    a('      return "<tr><td>" + e.time + "</td><td><span class=\\"badge badge-" + e.action + "\\">" + e.action + "</span></td><td>" + e.rule + "</td><td>" + e.host + "</td><td><code>" + escapeHtml(e.path) + "</code></td><td>" + e.client + "</td></tr>";')
    a("    });")
    a('    $("#waf-table tbody").innerHTML = rows.join("");')
    a("  }")
    a("  function renderCerts() {")
    a("    var rows = MOCK.certs.map(function (c) {")
    a('      var status = \'<span class="badge badge-exact">正常</span>\';')
    a('      if (c.status === "warn") status = \'<span class="badge badge-wildcard">即将过期</span>\';')
    a('      if (c.status === "expired") status = \'<span class="badge badge-block">已过期</span>\';')
    a('      return "<tr><td>" + c.domain + "</td><td>" + c.issuer + "</td><td>" + c.notAfter + "</td><td>" + c.daysLeft + "</td><td>" + status + "</td></tr>";')
    a("    });")
    a('    $("#certs-table tbody").innerHTML = rows.join("");')
    a("  }")
    a("  function initConfig() {")
    a('    $("#yaml-editor").value = savedYaml;')
    a('    $("#yaml-editor").addEventListener("input", function () { $("#validate-output").innerHTML = ""; });')
    a("  }")
    a("  function validateYaml() {")
    a('    var text = $("#yaml-editor").value;')
    a('    var out = $("#validate-output");')
    a('    if (text.indexOf("version:") < 0) {')
    a('      out.innerHTML = \'<p class="validate-err">缺少 version 字段（模拟校验）</p>\';')
    a("      return false;")
    a("    }")
    a('    if (text.indexOf("ERROR_DEMO") >= 0) {')
    a('      out.innerHTML = \'<p class="validate-err">rules[2].host: invalid regex（模拟）</p>\';')
    a("      return false;")
    a("    }")
    a('    out.innerHTML = \'<p class="validate-ok">✓ 校验通过（真实环境将调用 ingress validate）</p>\';')
    a("    return true;")
    a("  }")
    a("  function showDiff() {")
    a('    var cur = $("#yaml-editor").value.split("\\n");')
    a('    var base = savedYaml.split("\\n");')
    a("    var lines = [];")
    a("    var max = Math.max(cur.length, base.length);")
    a("    for (var i = 0; i < max; i++) {")
    a("      var a = base[i]; var b = cur[i];")
    a("      if (a === b) { if (a !== undefined) lines.push(\"  \" + a); }")
    a("      else {")
    a('        if (a !== undefined) lines.push(\'<span class="del">- \' + escapeHtml(a) + "</span>");')
    a('        if (b !== undefined) lines.push(\'<span class="add">+ \' + escapeHtml(b) + "</span>");')
    a("      }")
    a("    }")
    a('    $("#diff-content").innerHTML = lines.join("\\n") || "(无变更)";')
    a('    $("#modal-diff").classList.add("open");')
    a("  }")
    a("  function openPublishModal() {")
    a('    $("#publish-path").textContent = MOCK.instance.configPath;')
    a('    $("#publish-status").textContent = "";')
    a('    $$("#publish-steps li").forEach(function (li) { li.classList.remove("done", "active"); });')
    a('    $("#modal-publish").classList.add("open");')
    a("  }")
    a("  function closeModals() {")
    a('    $$(".modal-overlay").forEach(function (m) { m.classList.remove("open"); });')
    a("  }")
    a("  function delay(ms) { return new Promise(function (r) { setTimeout(r, ms); }); }")
    a("  function runPublish() {")
    a('    var steps = $$("#publish-steps li");')
    a('    var status = $("#publish-status");')
    a('    var yaml = $("#yaml-editor").value;')
    a("    steps[0].classList.add(\"active\");")
    a('    status.textContent = "正在校验…";')
    a("    return delay(600).then(function () {")
    a("      if (!validateYaml()) {")
    a('        status.textContent = "校验失败，已中止发布。";')
    a("        steps[0].classList.remove(\"active\");")
    a("        return;")
    a("      }")
    a("      steps[0].classList.remove(\"active\"); steps[0].classList.add(\"done\");")
    a("      steps[1].classList.add(\"active\");")
    a('      status.textContent = "正在写入 YAML…";')
    a("      return delay(800);")
    a("    }).then(function () {")
    a("      if (!steps[1].classList.contains(\"active\") && !steps[1].classList.contains(\"done\")) return;")
    a("      savedYaml = yaml.trim();")
    a("      steps[1].classList.remove(\"active\"); steps[1].classList.add(\"done\");")
    a("      steps[2].classList.add(\"active\");")
    a('      status.textContent = "正在发送 SIGHUP…";')
    a("      return delay(700);")
    a("    }).then(function () {")
    a("      if (!steps[2].classList.contains(\"active\") && !steps[2].classList.contains(\"done\")) return;")
    a('      MOCK.instance.lastReload = new Date().toLocaleString("zh-CN", { hour12: false });')
    a("      MOCK.instance.lastReloadOK = true;")
    a("      MOCK.instance.configHash = Math.random().toString(16).slice(2, 10);")
    a("      steps[2].classList.remove(\"active\"); steps[2].classList.add(\"done\");")
    a('      status.textContent = "发布成功。";')
    a("      renderOverview();")
    a('      toast("配置已保存并 reload");')
    a("      setTimeout(closeModals, 900);")
    a("    });")
    a("  }")
    a("  function searchLogs() {")
    a('    var q = $("#log-q").value.toLowerCase();')
    a('    var host = $("#log-host").value.toLowerCase();')
    a('    var status = $("#log-status").value;')
    a("    var lines = MOCK.accessLogs.filter(function (line) {")
    a("      if (host && line.toLowerCase().indexOf(host) < 0) return false;")
    a("      if (q && line.toLowerCase().indexOf(q) < 0) return false;")
    a("      if (status) {")
    a('        var m = line.match(/"\\s+(\\d{3})\\s/);')
    a("        if (!m || m[1].charAt(0) !== status) return false;")
    a("      }")
    a("      return true;")
    a("    });")
    a('    var container = $("#log-results");')
    a("    if (!lines.length) {")
    a(f'      container.innerHTML = \'<{T} class="empty-hint">无匹配日志</{T}>\';')
    a('      $("#log-count").textContent = "0 条";')
    a("      return;")
    a("    }")
    a("    container.innerHTML = lines.map(function (line) {")
    a('      var m = line.match(/"\\s+(\\d{3})\\s/);')
    a('      var cls = m ? "status-" + m[1].charAt(0) + "xx" : "";')
    a(f'      return \'<{T} class="log-line \' + cls + \'">\' + escapeHtml(line) + "</{T}>";')
    a("    }).join(\"\");")
    a('    $("#log-count").textContent = lines.length + " 条";')
    a("  }")
    a("  function bindEvents() {")
    a('    $("#route-filter").addEventListener("input", function (e) { renderRoutes(e.target.value); });')
    a('    $("#btn-match").addEventListener("click", runMatch);')
    a('    $("#waf-filter").addEventListener("change", function (e) { renderWafTable(e.target.value); });')
    a('    $("#btn-validate").addEventListener("click", validateYaml);')
    a('    $("#btn-diff").addEventListener("click", showDiff);')
    a('    $("#btn-save").addEventListener("click", function () {')
    a("      if (!validateYaml()) { toast(\"请先修复校验错误\", \"error\"); return; }")
    a('      savedYaml = $("#yaml-editor").value.trim();')
    a('      toast("已保存到 " + MOCK.instance.configPath);')
    a("    });")
    a('    $("#btn-publish").addEventListener("click", openPublishModal);')
    a('    $("#btn-publish-confirm").addEventListener("click", runPublish);')
    a('    $("#btn-quick-reload").addEventListener("click", function () { navigate("config"); openPublishModal(); });')
    a('    $$("[data-close-modal]").forEach(function (b) { b.addEventListener("click", closeModals); });')
    a('    $$(".modal-overlay").forEach(function (overlay) {')
    a("      overlay.addEventListener(\"click\", function (e) { if (e.target === overlay) closeModals(); });")
    a("    });")
    a('    $("#btn-log-search").addEventListener("click", searchLogs);')
    a('    $("#btn-log-clear").addEventListener("click", function () {')
    a('      $("#log-q").value = ""; $("#log-host").value = ""; $("#log-status").value = ""; searchLogs();')
    a("    });")
    a("  }")
    a("  function init() {")
    a("    initNav(); renderOverview(); renderRoutes(); renderWaf(); renderCerts(); initConfig(); searchLogs(); bindEvents();")
    a("  }")
    a('  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);')
    a("  else init();")
    a("})();")
    OUT.write_text("\n".join(lines) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    write_app()
