port: 80

# https_port: 443

ssl:
  - domain: example.com
    cert:
      certificate: /config/ssl/example.com/fullchain.pem
      certificate_key: /config/ssl/example.com/privkey.pem

waf:
  whiteHosts:
    - waf.example.com

rules:
  - host: portainer.example.com
    backend:
      service:
        name: portainer
        port: 80
  - host: docker-registry.example.com
    backend:
      service:
        name: docker-registry
        port: 80
    paths:
      - path: /v2
        backend:
          service:
            name: docker-registry-v2
            port: 80
  - host: httpbin.example.work
    backend:
      service:
        protocol: https
        name: httpbin.zcorky.com
        port: 443
  - host: httpbin2.example.work
    backend:
      service:
        protocol: https
        name: httpbin.org
        port: 443
  - host: handler.example.work
    backend:
      service:
        protocol: https
        name: httpbin.org
        port: 443
    paths:
      - path: /custom/handler/string
        backend:
          type: handler
          handler:
            body: Hello World!
      - path: /custom/handler/json
        backend:
          type: handler
          handler:
            headers:
              Content-Type: application/json
            body: |
              {
                "message": "Hello, World!"
              }
      - path: /custom/handler/html
        backend:
          type: handler
          handler:
            status_code: 200
            headers:
              Content-Type: text/html
            body: |
              <html>
                <body>
                  <h1>Hello, World!</h1>
                </body>
              </html>
